# Site Settings
title: Fed 2 Industry
email: contact@fed2industry.com
description: Resources for federal employees transitioning to industry careers.
author: "F2I Team"
baseurl: "/F2I"  # Add your repository name here
url: "https://conscious-change.github.io"  # Add your GitHub Pages URL here
markdown: kramdown

# Social Media
social:
  linkedin: "#"

# Contact Information
contact:
  phone: "(555) 123-4567"
  address: "1234 Federal Way, Washington, DC 20001"

# Build Settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # Remove the line below or change to _site
  # destination: ./docs

# Remove the entire responsive_image configuration block below
# responsive_image:
#  template: _includes/responsive-image-template.html
#  sizes:
#    - width: 400
#    - width: 800
#    - width: 1200
#    - width: 1600
#  base_path: assets/img
#  output_path_format: assets/img/responsive/%{dirname}/%{filename}-%{width}x%{height}.%{extension}
#  save_to_source: false
#  strip: true
#  quality: 85

# Content Collections
collections:
  resources:
    output: true
    permalink: /:collection/:name
  job_listings:
    output: true
    permalink: /:collection/:name

  guides:
    output: true
    permalink: /:collection/:name

# Collection Metadata (for reference, not used by Jekyll directly)
collection_meta:
  resources:
    title: "Resources"
    description: "Helpful resources for federal employees transitioning to the private sector"
  job_listings:
    title: "Job Listings"
    description: "Current job opportunities for federal employees"

  guides:
    title: "Transition Guides"
    description: "Step-by-step guides for various aspects of the federal-to-private transition"

# Default Layouts
defaults:
  - scope:
      path: "pages"
    values:
      layout: "page"

# Navigation Structure
navigation:
  - title: Home
    url: /
  - title: About
    url: /pages/about.html
  - title: Transition Resources
    children:
      - title: Transition Roadmap
        url: /pages/transition-roadmap.html
      - title: Self-Assessment
        url: /pages/self-assessment.html
      - title: Skill Translation
        url: /pages/skill-translation-hub.html
      - title: Resume & Branding
        url: /pages/resume-personal-branding.html
      - title: Networking
        url: /pages/networking-strategies.html
      - title: Job Search
        url: /pages/job-search-resources.html
      - title: Interview Prep
        url: /pages/interview-preparation.html
      - title: Compensation
        url: /pages/compensation-benefits.html
  - title: Community
    children:
      - title: Join Community
        url: /pages/community.html
      - title: Blog
        url: /pages/blog.html
  - title: Learning Center
    url: /pages/learning-center.html
