name: Jekyll Build and Test

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Install system dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential imagemagick libmagickwand-dev webp

    - name: Make scripts executable
      run: |
        chmod +x run_site.sh
        chmod +x scripts/process-images.sh

    - name: Install Bundler and handle version mismatches
      run: |
        # Install bundler
        gem install bundler

        # Check if we need to update bundler version in Gemfile.lock
        if grep -q "BUNDLED WITH" Gemfile.lock; then
          bundled_with_version=$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1 | tr -d ' ')
          installed_bundler_version=$(gem list bundler | grep -o "[0-9.]*" | head -n 1)

          echo "Gemfile.lock requires Bundler $bundled_with_version, installed version is $installed_bundler_version"

          if [ "$bundled_with_version" != "$installed_bundler_version" ]; then
            echo "Updating Gemfile.lock to use Bundler $installed_bundler_version..."
            sed -i "s/BUNDLED WITH.*$/BUNDLED WITH/" Gemfile.lock
            sed -i "s/   $bundled_with_version.*$/   $installed_bundler_version/" Gemfile.lock
          fi
        fi

    - name: Install dependencies
      run: bundle install

    - name: Process responsive images
      run: |
        ./scripts/process-images.sh --recursive

    - name: Build site with custom script
      run: |
        # Modify run_site.sh to build instead of serve in CI environment
        sed -i 's/bundle exec jekyll serve/bundle exec jekyll build --baseurl "\/F2I"/' run_site.sh
        # Run the script but skip the interactive prompts
        ./run_site.sh

    # - name: Run HTML tests
    #   run: |
    #     gem install html-proofer
    #     htmlproofer ./_site --disable-external --allow-hash-href --assume-extension true --ignore-empty-alt --ignore-missing-alt
   
    - name: Upload site artifact
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: _site/

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Download site artifact
      uses: actions/download-artifact@v4
      with:
        name: site
        path: _site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}
        publish_dir: ./_site
